# Generated by Django 5.0.6 on 2024-06-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restapi', '0004_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='miscellance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('destinantion', models.CharField(max_length=10)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
