# Generated by Django 5.0.6 on 2024-06-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restapi', '0005_miscellance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiddenfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hidden', models.CharField(max_length=100)),
            ],
        ),
    ]
