# Generated by Django 5.0.6 on 2024-06-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restapi', '0006_hiddenfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_joined', models.DateField()),
            ],
        ),
    ]
