# Generated by Django 5.0.6 on 2024-06-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restapi', '0007_user_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_new',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
