# Generated by Django 5.0.6 on 2024-05-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_musician_artist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artist',
            new_name='artist1',
        ),
    ]
