# Generated by Django 5.0.6 on 2024-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_teacher_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('l', 'large')], max_length=1)),
            ],
        ),
    ]
