# Generated by Django 5.0.6 on 2024-05-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='for_queryset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
