# Generated by Django 5.0.6 on 2024-05-31 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_meta_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meta_table',
        ),
    ]
