# Generated by Django 5.0.6 on 2024-05-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_meta_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='radio_button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('radio_button', models.CharField(choices=[('M', 'Male'), ('f', 'FEMale')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='meta_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'Meta',
                'ordering': ['-price'],
                'unique_together': {('name', 'created_at')},
            },
        ),
    ]
