# Generated by Django 5.0.6 on 2024-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='constraints',
            fields=[
                ('company_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('num', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=15)),
                ('salary', models.IntegerField(default=10000)),
            ],
        ),
        migrations.AddConstraint(
            model_name='constraints',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age_gte_18'),
        ),
    ]
