# Generated by Django 5.0.6 on 2024-06-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_constraints_constraints_age_gte_18'),
    ]

    operations = [
        migrations.CreateModel(
            name='green11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.CharField(default='dastgir', max_length=15)),
                ('senior', models.CharField(default='tannu', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='spartan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.CharField(default='sathish', max_length=15)),
                ('youngest_player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.green11')),
            ],
        ),
        migrations.AddField(
            model_name='green11',
            name='young_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.spartan'),
        ),
    ]
