# Generated by Django 5.0.6 on 2024-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='manyto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.CharField(max_length=15)),
                ('many', models.ManyToManyField(to='myapp.donor')),
            ],
        ),
    ]
