# Generated by Django 5.0.6 on 2024-06-10 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_manyto'),
    ]

    operations = [
        migrations.CreateModel(
            name='companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=15)),
                ('company_branch', models.CharField(max_length=15)),
                ('company_owner', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=15)),
                ('owner_name', models.CharField(max_length=15)),
                ('org_location', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=15)),
                ('emp_name', models.CharField(max_length=15)),
                ('emp_adress', models.CharField(max_length=15)),
                ('emp_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companys')),
            ],
        ),
        migrations.AddField(
            model_name='companys',
            name='company_org_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization'),
        ),
    ]
