# Generated by Django 5.0.6 on 2024-06-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_companys_organization_employess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employess',
            name='emp_salary',
            field=models.IntegerField(default=10000),
        ),
    ]
