# Generated by Django 5.0.6 on 2024-06-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_employess_emp_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('goes_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
