# Generated by Django 5.0.6 on 2024-06-12 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='for_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.great')),
                ('nothing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.rank')),
            ],
        ),
    ]
